defaults:
  - writer: wandb
  - metrics: example
  - datasets: onebatchtest
  - dataloader: example
  - transforms: basic
  - _self_
generator: 
  _target_: src.model.Generator
  kernels_combination: 1 # 3
  hidden_dim: 512 # 256
  MRF_block_type: 1 # 3
discriminator_mpd:
  _target_: src.model.DiscriminatorMPD
discriminator_msd:
  _target_: src.model.DiscriminatorMSD
optimizer_generator:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01
optimizer_discriminator_mpd:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01
optimizer_discriminator_msd:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01
lr_scheduler_generator:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.999
  step_size: ${trainer.epoch_len}
lr_scheduler_discriminator_mpd:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.999
  step_size: ${trainer.epoch_len}
lr_scheduler_discriminator_msd:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.999
  step_size: ${trainer.epoch_len}
loss_generator:
  _target_: src.loss.GeneratorLoss
loss_discriminator:
  _target_: src.loss.DiscriminatorLoss
trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 13000 # 13 101 total examples
  device_tensors: ["audio", "spectrogram"] # which tensors should be on device (ex. GPU)
  resume_from: null #"/Users/epbugaev/Documents/hse_year_4/dla-nv/saved/testing/checkpoint-epoch70.pth" # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max test_MulticlassAccuracy" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
