defaults:
  - writer: wandb
  - metrics: example
  - datasets: custom_texts
  - dataloader: inference
  - transforms: only_mel_spec
  - _self_
generator: 
  _target_: src.model.Generator
  kernels_combination: 1
  hidden_dim: 512
  MRF_block_type: 1
discriminator_mpd:
  _target_: src.model.DiscriminatorMPD
discriminator_msd:
  _target_: src.model.DiscriminatorMSD
inferencer:
  text_to_mel: True
  device_tensors: ["spectrogram", "audio"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "data/data_test/gen_from_texts" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/best_model.pth" # path to the pretrained model
