train:
  get_spectrogram: # special key for getting spectrogram
    _target_: src.transforms.MelSpectrogram
  audio:
    _target_: src.transforms.CutTransform
    cut_length: 2
inference:
  get_spectrogram:
    _target_: src.transforms.MelSpectrogram
  audio:
    _target_: src.transforms.CutTransform
    cut_length: 4
